### ISSUE TITLE
Hexn bot loop messages "Фарминг уже запущен"

### ISSUE THREAD

**Issue by netscrol2016** [TotalAwesome/BotFarmFactory#11]
Бот зависает в цикле, выводит сообщение Фарминг уже запущен и время следующего захода и так по кругу.

**Comment by TotalAwesome** [comment]
@Eynsteyn @lvu22292718 Это уже пофиксил?

**Comment by lvu22292718** [comment]
@TotalAwesome  Да, фиксил
@netscrol2016 Проблема еще наблюдается?
